<?php

namespace Database\Seeders;

use App\Models\CarMake;
use App\Models\CarModel;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CarModelSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        // $models = [
        //     'Ford' => ['Utility Police Interceptor Base', 'F-150 XLT', 'Mustang GT Premium', 'Transit Connect XLT', 'Utility Police Interceptor Base', 'Fusion SE', 'GT', 'Excursion Limited', 'Taurus X Limited', 'Explorer Timberline', 'Expedition Platinum', 'Expedition Max Limited', 'Shelby GT500 Base', 'Expedition Limited', 'Transit-350 XL', 'Transit-350 XLT', 'Shelby GT500 Base', 'Transit-350 XLT', 'Explorer XLT', 'Transit-350 XLT'],
        //     'Hyundai' => ['Palisade SEL', 'Elantra N Base', 'Tucson SE', 'Sonata Hybrid Limited', 'Elantra N Base', 'Kona N Base', 'Elantra GLS', 'Veloster Base', 'Equus Signature'],
        //     'Lexus' => ['RX 350 RX 350', 'RC 350 F Sport', 'LX 570 Base', 'IS 350 Base', 'LX 570 Three-Row', 'RC 350 Base', 'ES 330 Base', 'NX 350 F SPORT Handling', 'LX 470 Base', 'LS 460 L', 'LC 500 Base', 'GX 470 Base', 'NX 200t Base', 'GX 460 Base'],
        //     'INFINITI' => ['Q50 Hybrid Sport', 'Q70h Base', 'Q70 3.7', 'G37 x', 'G37 S Sport', 'M56 Base'],
        //     'Audi' => ['Q3 45 S line Premium Plus', 'S3 2.0T Premium Plus', 'Q5 2.0T Premium Plus', 'A4 2.0T Premium Plus quattro', 'A7 Premium', 'A3 2.0T', 'A5 2.0T Premium Plus', 'RS 5 2.9T', 'RS 7 4.0T Prestige', 'TT RS 2.5T', 'SQ5 3.0T Premium Plus', 'S7 4.0T Premium Plus', 'RS Q8 4.0T quattro', 'A5 2.0T Premium', 'Q7 3.0T Premium Plus', 'TTS 2.0T Premium Plus', 'SQ7 4.0T', 'S3 2.0T Tech Premium Plus', 'Q5 S line Premium Plus', 'A5 2.0T Premium Plus', 'R8 5.2 V10', 'RS 7 4.0T quattro'],
        //     'BMW' => ['740 iL', '440 Gran Coupe 440i xDrive', '650 Gran Coupe i xDrive', 'i3 120Ah w/Range Extender', '340 i', 'Z4 sDrive28i', 'M850 i xDrive', 'M4 CS', 'M4 Base', 'M4 Base', 'M6 Base', '435 Gran Coupe i', '525 i', '750 750i xDrive', '440 Gran Coupe i', '640 i', 'M8 Competition', 'i8 Base', 'X4 M40i', 'M4 Base', '540 i xDrive', 'M5 Base', 'X5 3.0i', 'X7 xDrive40i', '540 i xDrive', 'X1 sDrive28i', 'M6 Base', 'X6 sDrive35i', 'M4 Base', 'M550 i xDrive', '540 i xDrive', 'M4 Base', 'X1 xDrive28i', 'M4 Base', 'X6 xDrive40i', 'X5 3.0i'],
        //     'Tesla' => ['Model X Long Range Plus', 'Model 3 Performance', 'Model Y Performance', 'Model X Base', 'Model 3 Standard Range Plus', 'Model X Long Range'],
        //     'Land Rover' => ['Range Rover Sport 3.0 Supercharged HST', 'LR4 HSE', 'LR4 HSE LUX Landmark Edition', 'Range Rover Sport 3.0L Supercharged HSE', 'Discovery Sport SE R-Dynamic', 'Discovery HSE', 'Range Rover Evoque Pure', 'Discovery Sport HSE', 'Range Rover Autobiography', 'Range Rover Supercharged', 'Defender X-Dynamic SE'],
        //     'Mercedes-Benz' => ['Metris Base', 'AMG CLA 45 Base 4MATIC', 'AMG C 43 Base 4MATIC', 'AMG C 63 S', 'CLA-Class CLA 250', 'GLK-Class GLK 350', 'AMG GL AMG GL 63 4MATIC', 'C-Class C300 4MATIC', 'AMG C AMG C 63', 'GLE 450 GLE 450', 'Sprinter High Roof', 'AMG GLS 63 4MATIC', 'SL-Class SL 550', 'AMG GLA 45 Base 4MATIC', 'SL-Class SL500 Roadster', 'CLS-Class CLS 550', 'AMG G 63 Base', 'AMG G 63 Base', 'EQS 450 4MATIC', 'AMG GLC 63 Base 4MATIC', 'AMG E 53 4MATIC', 'AMG GLS 63 4MATIC', 'AMG C 43 Base 4MATIC', 'AMG C AMG C 63', 'GLS 450 Base 4MATIC', 'EQS 450+ Base', 'SLC 300 Base', 'Sprinter 4500 High Roof', 'Maybach S S 600', 'CLK-Class 500 Cabriolet', 'CLK-Class CLK 350', 'AMG GLS 63 4MATIC', 'AMG G 63 Base', 'AMG G 63 Base', 'AMG GLS 63 4MATIC', 'AMG GLA 45 Base 4MATIC'],
        //     'Acura' => ['ILX 2.4L', 'RL Technology', 'ILX 2.0L w/Premium Package', 'Integra w/A-Spec Tech Package', 'MDX 3.7L Advance', 'RSX Type S', 'TLX w/A-Spec Package'],
        //     'Chevrolet' => ['S-10 LS', 'Suburban RST', 'Silverado 1500 Custom Trail Boss', 'Express 1500 Work Van', 'Monte Carlo SS', 'Corvette Base', 'Trailblazer LS', 'Blazer Premier', 'Traverse Premier', 'Corvette Stingray w/1LT', 'Express 1500 Work Van', 'Avalanche LTZ', 'Bolt EUV Premier'],
        //     'Jaguar' => ['F-TYPE', 'F-TYPE R', 'XF 35t R-Sport'],
        //     'Kia' => ['Sorento SX', 'Niro Plug-In Hybrid EX Premium', 'Sportage Nightfall', 'Sportage SX Turbo', 'Sportage X-Pro', 'Telluride SX', 'Optima EX', 'Stinger GT2', 'K900 5.0L', 'Forte GT-Line'],
        //     'Jeep' => ['New Compass Trailhawk', 'Grand Cherokee Summit', 'Gladiator Rubicon', 'Wrangler Unlimited Sahara'],
        //     'Porsche' => ['Cayenne Platinum Edition', '911 Carrera S', 'Cayman GTS', 'Cayman Base', '911 Carrera S', 'Panamera 2', '718 Boxster Base', '911 GT2 RS', 'Cayman S', 'Cayenne Platinum Edition', '911 Carrera C2S', 'Cayenne E-Hybrid S', '718 Cayman S', 'Cayman S', '911 Carrera 4S'],
        //     'Bentley' => ['Continental GTC Base', 'Continental GT W12', 'Arnage R', 'Bentayga S'],
        //     'Lincoln' => ['Aviator Reserve AWD', 'MKZ Hybrid Base', 'Aviator Reserve AWD', 'MKZ Base', 'Navigator L', 'MKX Base', 'MKZ Reserve', 'Town Car Base', 'Navigator L Reserve', 'MKC Select', 'Corsair Grand Touring'],
        //     'Cadillac' => ['CT5 Premium Luxury', 'CT5-V Blackwing', 'CT5-V V-Series', 'XT4 Sport', 'DTS Base', 'ATS 3.6L Luxury', 'XTS Luxury', 'CTS 2.0L Turbo Luxury', 'DTS Luxury II'],
        //     'Lucid' => ['Air Grand Touring', 'Air Pure'],
        //     'MINI' => ['Convertible John Cooper Works'],
        //     'Volvo' => ['XC90 Hybrid T8 R-Design', 'XC90 3.2', 'S90 T5 Momentum'],
        //     'Hummer' => ['H2 Base'],
        //     'RAM' => ['ProMaster 3500 High Roof', '2500 Laramie', '1500 Laramie', 'ProMaster 2500 Window Van High Roof', '1500 Big Horn'],
        //     'Scion' => ['tC Base'],
        //     'Mazda' => ['CX-9 Grand Touring', 'Mazda6 Grand Touring', 'Mazda3 s Grand Touring', 'CX-30 Premium Package'],
        //     'Alfa Romeo' => ['Stelvio Ti Sport', 'Giulia Quadrifoglio', 'Stelvio Ti'],
        //     'Ferrari' => ['FF Base', 'Roma Base'],
        //     'Bugatti' => ['Veyron 16.4 Grand Sport'],
        //     'Polestar' => ['2 Launch Edition'],
        //     'Subaru' => ['Forester 2.5i Limited', 'Legacy 2.5i Limited', 'Outback 2.5i Limited', 'Impreza 2.0i Premium'],
        //     'Tesla' => ['Model S Plaid', 'Model 3 Standard Range Plus', 'Model X Long Range Plus', 'Model Y Performance']
        // ];
        $models = [
            'Ford' => ['Utility Police Interceptor Base', 'F-150 XLT', 'Mustang GT Premium', 'F-150 SVT Raptor', 'Bronco Wildtrak Advanced', 'F-250 Lariat', 'F-250 Platinum', 'F-250 King Ranch', 'F-250 XLT SuperCab Super Duty', 'F-150 Lariat', 'F-150 Platinum', 'F-150 XL', 'Shelby GT500 Base', 'Shelby GT350R Base', 'GT', 'Expedition Platinum', 'Expedition Limited', 'Expedition King Ranch', 'Expedition Max Limited', 'Expedition Max King Ranch', 'Expedition EL XLT', 'Explorer XLT', 'Explorer Timberline', 'Explorer sport', 'Escape XLT', 'Escape Limited', 'Escape SE', 'Edge Sport', 'Edge SEL', 'Fusion SE', 'Fusion Energi Titanium', 'Fusion Hybrid SE', 'Taurus X Limited', 'Transit Connect XLT', 'Transit Connect XL', 'Transit Connect XL w/Rear Symmetrical Doors', 'Transit-350 XL', 'Transit-350 XLT', 'Transit-350 Base', 'E150 XLT', 'E350 Super Duty XLT', 'Ranger Sport SuperCab', 'Bronco Sport Outer Banks', 'Bronco Sport Big Bend', 'Bronco Raptor', 'Bronco', 'Maverick Lariat', 'C-Max Energi SE', 'Focus RS Base', 'Mustang Mach-E Select', 'Mustang Mach-E Premium', 'Mustang Mach-E California Route 1', 'Mustang Base', 'Mustang V6', 'Mustang EcoBoost Premium', 'Mustang GT'],
            'Hyundai' => ['Palisade SEL', 'Elantra N Base', 'Tucson SE', 'Santa Fe SEL', 'Sonata Hybrid Limited', 'Kona N Base', 'Veloster Base', 'Veloster Turbo R-Spec', 'Genesis Coupe 3.8 Grand Touring', 'Genesis Coupe 3.8 R-Spec', 'Equus Signature', 'Santa Cruz 2.5T Limited', 'IONIQ Plug-In Hybrid SEL', 'Genesis 3.8', 'Genesis 4.6', 'Elantra GLS', 'Santa Fe SE', 'Santa Fe SEL Plus 2.4', 'Tucson Limited', 'Tucson Hybrid SEL Convenience', 'Elantra N Base'],
            'Lexus' => ['RX 350 RX 350', 'RC 350 F Sport', 'LX 570 Base', 'IS 350 Base', 'LX 570 Three-Row', 'LC 500 Base', 'ES 330 Base', 'ES 300h Base', 'ES 350 Base', 'GX 470 Base', 'GX 460 Base', 'NX 200t Base', 'NX 350 F SPORT Handling', 'RX 300 Base', 'RX 450h Base', 'RX 350 Base', 'LS 460 L', 'LS 460 Crafted Line', 'LS 500 Base', 'IS 250 Base', 'IS 250C Base', 'RC 350 Base', 'LX 600 F SPORT', 'LX 600 Premium', 'CT 200h Premium', 'GS 350 Base', 'GS 350 F Sport', 'RX 350 F Sport', 'RX 450h F SPORT Handling', 'IS-F Base', 'LC 500 Base', 'LX 470 Base'],
            'INFINITI' => ['Q50 Hybrid Sport', 'Q70h Base', 'Q70 3.7', 'Q70 3.7X', 'QX70 Base', 'QX80 Base', 'QX60 Base', 'QX60 Pure', 'QX30 Premium', 'G35 Sport', 'G37 x', 'G37 S Sport', 'Q40 Base', 'Q50 Premium', 'Q50 Hybrid Premium', 'M56 Base', 'FX50 Base'],
            'Audi' => ['Q3 45 S line Premium Plus', 'S3 2.0T Premium Plus', 'A7 Premium', 'A5 2.0T Premium Plus', 'RS 5 2.9T', 'Q5 2.0T Premium Plus', 'A4 2.0T Premium Plus quattro', 'A3 2.0T', 'R8 5.2 V10', 'RS 7 4.0T Prestige', 'A8 4.0', 'Q7 3.0T Premium Plus', 'A7 Premium Plus', 'TT 2.0T', 'S7 4.0T Premium Plus', 'SQ5 3.0T Premium Plus', 'A6 2.0T Premium Plus', 'RS Q8 4.0T quattro', 'A3 2.0 TDI Premium Plus', 'S4 3.0T Premium', 'S5 3.0T Premium Plus', 'RS 3 2.5T', 'A5 2.0T Premium', 'A8 L 55', 'A8 L 4.0T', 'e-tron Prestige', 'Q4 e-tron Sportback Premium', 'Q8 55 Premium Plus', 'RS 5 4.2', 'S8 4.0T Plus', 'A7 55 Premium', 'A7 3.0T Prestige', 'A7 3.0T Premium Plus', 'Q5 Premium', 'Q5 S line Premium Plus', 'Q7 Premium Plus', 'Q7 55 Prestige', 'Q7 45 Premium Plus', 'SQ7 4.0T', 'TT RS 2.5T', 'TTS 2.0T Premium Plus', 'S5 4.2 Premium Plus', 'S6 4.0T', 'S8 4.2 quattro', 'A4 2.0T Premium', 'A3 2.0T Premium', 'A3 2.0T Tech Premium', 'allroad 2.7T', 'R8 Base', 'R8 5.2', 'RS 7 4.0T', 'RS 7 4.0T Performance Prestige', 'RS 7 4.0T quattro', 'S4 4.2 quattro', 'S5 3.0T Prestige', 'SQ5 3.0T Prestige', 'SQ5 3.0T Premium', 'TT 3.2 Cabriolet quattro'],
            'Acura' => ['ILX 2.4L', 'RL Technology', 'MDX 3.7L Advance', 'RSX Type S', 'TL Technology', 'TLX w/A-Spec Package', 'TLX V6 Advance', 'MDX w/Technology Package', 'MDX 3.5L Technology Package', 'MDX 3.5L w/Advance & Entertainment Pkgs', 'RDX Technology Package', 'RDX Advance Package', 'ILX 2.0L w/Premium Package', 'ILX Premium Package', 'Integra w/A-Spec Tech Package', 'Integra LS', 'ZDX Base'],
            'BMW' => ['740 iL', '440 Gran Coupe 440i xDrive', '650 Gran Coupe i xDrive', 'i3 120Ah w/Range Extender', '340 i', 'Z4 sDrive28i', 'M850 i xDrive', '525 i', '750 750i xDrive', '540 i xDrive', '328 xi', 'M235 i', '435 Gran Coupe i', '740 Li', 'M760 i xDrive', '750 Li xDrive', '640 i', '135 i', '328 i xDrive', '328 i', '323 Ci', '335 i', '435 i', '528 i xDrive', '530e Base', '650 i', '740 i', 'M340 i xDrive', 'M440 i', 'M440 i xDrive', 'M550 i xDrive', 'M760 M760i xDrive', 'ALPINA B7 ALPINA B7 xDrive', 'ALPINA B7 Base', 'X5 3.0i', 'X4 M40i', 'X7 xDrive40i', 'X6 sDrive35i', 'X6 xDrive40i', 'X6 xDrive50i', 'X1 sDrive28i', 'X1 xDrive28i', 'X3 xDrive30i', 'X3 M40i', 'X5 xDrive40i', 'X5 xDrive50i', 'X5 PHEV xDrive45e', 'X5 eDrive xDrive40e', 'X5 M Base', 'X6 M Base', 'X7 M50i', 'X7 ALPINA XB7', 'X2 xDrive28i', 'Z4 2.5i Roadster', 'Z4 3.0i Roadster', 'Z4 sDrive35is', 'M2 Base', 'M2 Competition', 'M3 Base', 'M3 CS', 'M4 Base', 'M4 CS', 'M4 Competition xDrive', 'M5 Base', 'M5 Competition', 'M6 Base', 'M6 Gran Coupe Base', 'M8 Base', 'M8 Competition', 'i8 Base', 'i3 Base w/Range Extender', '330e iPerformance', '330 330i xDrive', '430 i xDrive', '435 Gran Coupe i', '440 i xDrive', '550 Gran Turismo i'],
            'Mercedes-Benz' => ['Metris Base', 'AMG CLA 45 Base 4MATIC', 'AMG C 43 Base 4MATIC', 'AMG C 63 S', 'AMG G 63 Base', 'GLS 450 Base 4MATIC', 'AMG GT AMG GT S', 'AMG GLE AMG GLE 63 S-Model 4MATIC', 'AMG GLE 53 AMG GLE 53', 'AMG GLS 63 4MATIC', 'AMG E 63 S 4MATIC', 'AMG E 53 4MATIC', 'AMG E 53 Base 4MATIC', 'AMG C 63 Base', 'AMG C AMG C 63', 'AMG C AMG C 63 S', 'AMG GL AMG GL 63 4MATIC', 'AMG GLE 43 Coupe 4MATIC', 'AMG GLC 63 Base 4MATIC', 'AMG GLA 45 Base 4MATIC', 'AMG GT 53 Base', 'AMG GT 63 S 4-Door', 'AMG GT C', 'AMG S 63 Base 4MATIC', 'AMG E 63 S 4MATIC', 'AMG G 63 4MATIC', 'AMG C 43 AMG C 43 4MATIC', 'EQS 450 4MATIC', 'EQS 450+ Base', 'S-Class S 580 4MATIC', 'S-Class S 560', 'S-Class S 560 4MATIC', 'S-Class S 63 AMG', 'S-Class S 550 4MATIC', 'S-Class S 600', 'G-Class G 550 4MATIC', 'G-Class G 550', 'GL-Class GL 550', 'GL-Class GL 550 4MATIC', 'GL-Class GL 450', 'GL-Class GL 450 4MATIC', 'GLS 550 Base 4MATIC', 'GLE 350 Base 4MATIC', 'GLE 450 GLE 450', 'GLC 300 GLC 300', 'GLC 300 Base 4MATIC', 'GLA 250 Base 4MATIC', 'CLA-Class CLA 250', 'CLS-Class CLS 550', 'CLS-Class CLS500', 'E-Class E 550', 'E-Class E 350', 'E-Class E 350 4MATIC', 'E-Class E 300 4MATIC', 'E-Class E 400', 'E-Class E 400 4MATIC', 'E-Class 400E', 'C-Class C300 4MATIC', 'C-Class C 300 4MATIC', 'C-Class C 300 4MATIC Sport', 'C-Class C280 4MATIC', 'SL-Class SL 550', 'SL-Class SL500 Roadster', 'SLK-Class SLK230 Kompressor', 'SLK-Class SLK 350', 'CLK-Class 500 Cabriolet', 'CLK-Class CLK 350', 'CLK-Class 550', 'SLC 300 Base', 'Maybach S S 600', 'Sprinter 2500', 'Sprinter 3500 High Roof', 'Sprinter 3500XD High Roof', 'Sprinter 4500 High Roof', 'Sprinter High Roof', 'Sprinter Normal Roof', 'Metris Base', 'E-Class E 300 4MATIC', 'E-Class E 350 4MATIC', 'GLS 450 Base', 'S-Class S 580', 'S-Class S 63 AMG', 'CLK-Class CLK 350', 'GLA-Class GLA 250 4MATIC', 'GLC 300 Base 4MATIC', 'AMG C 43 Base'],
            'Toyota' => ['Supra 3.0 Premium', 'Corolla LE', 'Avalon Touring', 'GR Corolla Circuit Edition', 'Tacoma PreRunner', '4Runner SR5', 'Highlander XLE', 'Land Cruiser Base', 'RAV4 Hybrid XLE', 'Sequoia Platinum', 'Tundra Hybrid TRD Pro', 'Camry Hybrid LE', 'Camry LE', 'Sienna LE', 'Yaris Base', 'Matrix XRS', 'Tundra SR5', 'Tundra SR5 Access Cab', 'Tundra 1794', 'Tundra Limited', 'Tundra Hybrid Limited', 'Tacoma Double Cab', 'Tacoma TRD Pro', '4Runner Limited', '4Runner TRD Pro', '4Runner Trail', 'Highlander Limited', 'Highlander Hybrid Limited', 'Highlander Hybrid Limited Platinum', 'Highlander SE', 'Highlander Base', 'Camry SE', 'Camry Hybrid XLE', 'Camry Solara SLE V6', 'Corolla Hybrid LE', 'Corolla iM Base', 'GR86 Premium', 'Supra A91 Edition', 'Supra A91-MT Edition', 'FJ Cruiser Base', 'bZ4X Limited'],
            'Honda' => ['Passport Elite', 'CR-V EX-L', 'Civic LX', 'Ridgeline RTL-E', 'Accord EX-L', 'S2000 CR', 'S2000 Base', 'Pilot EX', 'Insight EX', 'Civic EX', 'Civic Si'],
            'Dodge' => ['Challenger SXT', 'Ram 1500 Laramie Mega Cab', 'Sprinter 2500', 'Challenger R/T Scat Pack', 'Challenger SRT Hellcat', 'Challenger R/T', 'Ram 2500 Laramie', 'Ram 1500 Laramie', 'Ram 1500 ST', 'Ram 1500 SRT-10', 'Ram 1500 SRT-10 Quad Cab', 'Ram 2500 SLT', 'Ram 2500 SLT Quad Cab', 'Ram 2500 Tradesman', 'Ram 3500 Laramie', 'Durango GT', 'Caliber Express', 'Dart SE', 'Magnum R/T', 'Charger R/T', 'Charger Scat Pack', 'Viper GTC', 'Dakota SLT', 'Dakota SLT Quad Cab'],
            'Chevrolet' => ['S-10 LS', 'Suburban RST', 'Silverado 1500 Custom Trail Boss', 'Camaro 1LT', 'Corvette Base', 'Trailblazer LS', 'Malibu LTZ', 'Blazer Premier', 'Traverse Premier', 'Express 1500 Work Van', 'Express 3500 Base', 'Monte Carlo SS', 'Avalanche LTZ', 'Tahoe High Country', 'Tahoe LTZ', 'Tahoe Premier', 'Tahoe LT', 'Suburban LT', 'Suburban 1500 LT', 'Suburban 1500 LTZ', 'Suburban 2500 LS', 'Suburban Premier', 'Suburban 2500', 'Silverado 1500 LT Crew Cab', 'Silverado 1500 1LT', 'Silverado 3500 LTZ', 'Silverado 3500 High Country', 'Colorado Z71', 'Colorado Z85', 'Bolt EUV Premier', 'Sonic LT', 'SSR Base', 'Corvette Stingray w/1LT', 'Corvette Z06', 'Camaro ZL1', 'Camaro 1SS', 'Camaro 2SS', 'Camaro 2LT', 'Camaro LT1', 'Express 3500 LT', 'Trailblazer RS', 'Trailblazer LT', '1500 Cheyenne Extended Cab', 'Corvette Base'],
            'Nissan' => ['350Z Enthusiast', 'Sentra SR', 'Rogue SV', 'GT-R Premium', 'Armada SL', 'Titan XD SV', '370Z Base', '370Z Touring', '370Z NISMO', 'Leaf S', 'Leaf SL', 'Leaf SV PLUS', 'Pathfinder SL', 'Murano SL', 'Juke SV', 'Frontier SL', 'Xterra S', 'NV Passenger NV3500 HD SL V8', 'Versa 1.8 S', 'Maxima SV', 'Rogue S', 'Rogue SL', 'Titan SE', 'Titan XD S', 'Z Proto Spec'],
            'Land Rover' => ['Rover Range Rover Sport 3.0 Supercharged HST', 'Rover LR4 HSE', 'Rover Range Rover Supercharged', 'Rover Discovery Sport SE R-Dynamic', 'Rover Range Rover Velar SVAutobiography Dynamic Edition', 'Rover Range Rover Evoque Pure', 'Rover Range Rover Sport HSE', 'Rover Range Rover Sport SVR', 'Rover Range Rover 5.0L Supercharged Autobiography', 'Rover Range Rover 5.0L Supercharged Autobiography LWB', 'Rover Range Rover P525 HSE SWB', 'Rover Range Rover P525 Westminster', 'Rover Range Rover P400 SE SWB', 'Rover Range Rover P530 SE LWB 7 Seat', 'Rover Range Rover 3.0L Supercharged HSE', 'Rover Range Rover 3.0L Supercharged', 'Rover Range Rover Sport First Edition', 'Rover Range Rover Sport HST MHEV', 'Rover Range Rover Sport Supercharged', 'Rover Range Rover Sport 3.0L Supercharged HSE', 'Rover Range Rover Evoque SE', 'Rover Range Rover Evoque SE Premium', 'Rover Range Rover Evoque S', 'Rover Range Rover Evoque R-Dynamic HSE', 'Rover Range Rover Velar P250 SE R-Dynamic', 'Rover Range Rover Velar P250 S R-Dynamic', 'Rover Range Rover Velar R-Dynamic SE', 'Rover Range Rover Autobiography', 'Rover Range Rover SV Autobiography Dynamic SWB', 'Rover Defender X', 'Rover Defender S', 'Rover Defender SE', 'Rover Defender X-Dynamic SE', 'Rover Discovery HSE', 'Rover Discovery Sport HSE', 'Rover Discovery Sport S R-Dynamic', 'Rover LR3 HSE', 'Rover LR4 HSE LUX Landmark Edition', 'Rover LR4 Lux'],
            'Porsche' => ['Cayenne Platinum Edition', '911 Carrera S', 'Cayenne Base', '718 Boxster Base', 'Panamera 2', '911 GT2 RS', 'Cayman GTS', '718 Cayman S', 'Macan S', 'Cayenne GTS', '911 Carrera 4S', '911 Carrera Turbo', '911 Carrera C2S', '911 R', '911 Carrera 4 Cabriolet', '911 Carrera S Cabriolet', 'Boxster S', 'Boxster RS 60 Spyder', 'Cayman S', 'Cayman Base', 'Panamera Turbo', 'Panamera 4S', 'Panamera GTS', 'Panamera Base', 'Taycan Turbo', 'Taycan Base', 'Macan Base', 'Cayenne E-Hybrid S', 'Cayenne S', '718 Spyder Base'],
            'Tesla' => ['Model X Long Range Plus', 'Model 3 Performance', 'Model Y Performance', 'Model X Base', 'Model 3 Standard Range Plus', 'Model Y Long Range', 'Model S 70D', 'Model X P90D', 'Model X Performance'],
            'Lincoln' => ['Aviator Reserve AWD', 'Navigator L', 'MKZ Hybrid Base', 'MKZ Base', 'Navigator Base', 'Navigator Select', 'Navigator Reserve', 'Navigator Premiere', 'Navigator L Reserve', 'MKC Select', 'MKC Reserve', 'MKX Base', 'MKX Reserve', 'MKS EcoBoost', 'Town Car Base', 'Town Car Signature', 'Corsair Grand Touring', 'Corsair Reserve', 'Nautilus Reserve'],
            'Jaguar' => ['F-TYPE', 'F-TYPE R', 'XF 35t R-Sport', 'XF S', 'XF XFR-S', 'F-PACE S', 'F-PACE 25t Premium', 'F-PACE 30t R-Sport', 'F-PACE SVR', 'XE 25t', 'XJ Base', 'XJ Vanden Plas', 'XJ8 Base', 'XKR Base'],
            'Genesis' => ['GV70 3.5T Sport', 'G90 3.3T Premium', 'G70 2.0T', 'G70 3.3T', 'G80 2.5T', 'G80 3.8', 'G80 3.3T Sport', 'GV70 2.5T', 'GV80 2.5T', 'G90 5.0 Ultimate'],
            'Kia' => ['Sorento SX', 'Niro Plug-In Hybrid EX Premium', 'Sportage Nightfall', 'Sportage SX Turbo', 'Forte GT-Line', 'Stinger GT2', 'Telluride SX', 'K900 5.0L', 'Optima EX', 'Optima Hybrid LX', 'Optima Hybrid EX', 'Optima LX', 'Soul Base', 'Sorento LX', 'Sorento EX', 'Sportage LX', 'Sportage Plug-In Hybrid X-Line', 'Sportage X-Pro', 'Telluride EX', 'Telluride S', 'Telluride LX', 'EV6 GT-Line', 'EV6 Wind', 'K5 EX', 'K5 GT-Line', 'Seltos S'],
            'Volvo' => ['XC90 Hybrid T8 R-Design', 'S90 T5 Momentum', 'V60 Cross Country T5', 'XC90 T6 Momentum', 'XC90 T6 Inscription', 'XC90 Recharge Plug-In Hybrid T8 Inscription 7 Passenger', 'XC60 Recharge Plug-In Hybrid T8 Inscription', 'S80 3.2', 'S60 T6 Momentum', 'V60 T6 R-Design Platinum', 'C30 T5 Premier Plus', 'XC70 3.2', 'C40 Recharge Pure Electric Twin Ultimate'],
            'Mazda' => ['CX-9 Grand Touring', 'MX-5 Miata Grand Touring', 'Mazda6 Grand Touring', 'CX-30 Premium Package', 'Mazda3 s Grand Touring', 'MX-5 Miata RF Grand Touring', 'CX-7 Grand Touring', 'MazdaSpeed3 Grand Touring', 'Mazda3 Touring', 'Mazda3 i Touring', 'Mazda3 FWD w/Premium Package', 'CX-90 Premium', 'MX-5 Miata Base', 'CX-30 2.5 S Select Package', 'Mazda6 Touring', 'Mazda6 i Grand Touring', 'Mazda6 Grand Touring Reserve'],
            'Subaru' => ['Forester 2.5 X', 'BRZ Premium', 'Outback 3.6R Touring', 'Impreza WRX STI', 'Impreza WRX Sti', 'WRX Base', 'WRX Premium', 'WRX Limited', 'Legacy 2.5 i Premium', 'Forester Premium', 'Forester Base', 'Forester 2.5 XT', 'Impreza 2.0i Sport', 'Impreza WRX Premium', 'Outback 2.5i Limited', 'Outback 3.0 R VDC Limited'],
            'Volkswagen' => ['Golf R 20th Anniversary Edition', 'Arteon 2.0T SE', 'Eurovan MV', 'Jetta 1.4T SE', 'Golf GTI 2.0T S 4-Door', 'Golf R 4-Door w/DCC & Navigation', 'Tiguan 2.0T SE', 'Atlas Cross Sport 3.6L V6 SEL Premium', 'Beetle 1.8T', 'Beetle 2.0T S', 'Jetta GLX VR6', 'Touareg V6 Executive', 'Touareg VR6 Lux', 'Arteon SEL R-Line', 'Arteon 2.0T SEL Premium R-Line', 'Golf R 4-Door', 'Routan SE'],
            'Bentley' => ['Continental GTC Base', 'Bentayga S', 'Continental GT Base', 'Continental GT Speed', 'Continental GT V8', 'Flying Spur V8', 'Bentayga Azure First Edition', 'Bentayga Onyx Edition', 'Bentayga Speed', 'Bentayga V8', 'Arnage R'],
            'Maserati' => ['Quattroporte S', 'Ghibli S Q4', 'Levante S', 'GranTurismo Sport', 'Quattroporte Modena Q4', 'Quattroporte S Q4 GranLusso', 'Quattroporte Base', 'Ghibli S Q4 GranSport', 'Ghibli S Q4 GranLusso', 'GranTurismo Base', 'GranTurismo MC', 'MC20 MC20', 'Grecale Modena', 'Levante Modena'],
            'Aston Martin' => ['DBS Superleggera', 'DBX Base', 'V8 Vantage Base'],
            'Lamborghini' => ['Huracan Tecnica Coupe', 'Gallardo Base', 'Huracan LP580-2', 'Huracan LP580-2S', 'Huracan EVO Base', 'Murcielago Base', 'Aventador SVJ Base', 'Urus Base'],
            'Ferrari' => ['FF Base', 'Roma Base', '488 GTB Base', 'California T'],
            'Rolls-Royce' => ['Phantom Drophead Coupe Drophead', 'Ghost Base', 'Cullinan'],
            'Alfa Romeo' => ['Stelvio Ti Sport', 'Giulia Quadrifoglio', 'Stelvio Quadrifoglio', 'Giulia Ti', 'Stelvio Ti'],
            'GMC' => ['Acadia SLT-1', 'Terrain SLE', 'Sierra 1500 SLT', 'Yukon XL SLT', 'Acadia Denali', 'Acadia SLE', 'Terrain SLT', 'Terrain SLT-1', 'Sierra 2500 SLE', 'Sierra 2500 AT4', 'Sierra 3500 SLE', 'Yukon Denali', 'Yukon XL Denali', 'Yukon XL AT4', 'Suburban 2500', 'Sierra 1500 Denali', 'Sierra 1500 SLE Crew Cab', 'Sierra 2500 Base', 'Sierra 2500 SLE H/D Extended Cab'],
            'Cadillac' => ['CT5 Premium Luxury', 'Escalade Sport Platinum', 'CTS 2.0L Turbo Luxury', 'Escalade ESV Sport', 'Escalade Premium', 'Escalade Luxury', 'Escalade Premium Luxury Platinum', 'Escalade ESV Platinum', 'Escalade ESV Premium Luxury', 'Escalade ESV Luxury', 'Escalade EXT Base', 'ATS 3.6L Luxury', 'ATS 2.5L', 'XTS Luxury', 'CT5-V Blackwing', 'CT5-V V-Series', 'CT4 Luxury', 'CTS-V Base', 'CTS Premium', 'CTS Luxury', 'XT4 Sport', 'XT6 Sport AWD', 'DTS Base', 'DTS Luxury II', 'DTS Luxury', 'SRX Luxury Collection'],
            'Chrysler' => ['300 Touring', 'Pacifica Touring', '300C SRT8', 'Pacifica Hybrid Touring L', 'Crossfire Limited'],
            'Buick' => ['Verano Convenience', 'Encore GX Essence', 'LaCrosse Base', 'Lucerne CXL', 'Rainier CXL', 'Roadmaster Estate', 'Encore Preferred'],
            'RAM' => ['ProMaster 3500 High Roof', '1500 Laramie', '2500 Laramie', '3500 Laramie', '1500 Big Horn', '1500 Limited', '1500 Longhorn', '1500 TRX', '1500 SLT', '1500 Classic Warlock', '1500 Classic SLT', '2500 Big Horn', '2500 SLT', '2500 Tradesman', 'ProMaster 2500 High Roof', 'ProMaster 2500 Window Van High Roof'],
            'FIAT' => ['124 Spider Abarth', '500e Battery Electric'],
            'Saturn' => ['Sky Base', 'Sky Red Line'],
            'Scion' => ['tC Base', 'tC Release Series 6.0', 'tC Anniversary Edition'],
            'Pontiac' => ['Firebird Base'],
            'Saab' => ['9-3 SE'],
            'Mercury' => ['Marauder Base'],
            'Hummer' => ['H2 Base', 'H2 SUT'],
            'McLaren' => ['570S Spider'],
            'Lotus' => ['Evora 400 Base'],
            'Bugatti' => ['Veyron 16.4 Grand Sport'],
            'Karma' => ['Revero Base'],
            'Polestar' => ['2 Launch Edition'],
            'Rivian' => ['R1S Adventure Package', 'R1S Launch Edition'],
            'Lucid' => ['Air Grand Touring', 'Air Pure'],
            'MINI' => ['Convertible John Cooper Works', 'Cooper S Clubman Base', 'Countryman Cooper S ALL4', 'Hardtop Cooper S'],
            'Jeep' => ['New Compass Trailhawk', 'Grand Cherokee Summit', 'Gladiator Rubicon', 'Wrangler Unlimited Sahara', 'Grand Cherokee L Limited', 'Grand Cherokee L Summit', 'Grand Cherokee L Overland', 'Grand Cherokee L Laredo', 'Wrangler Unlimited Sport', 'Wrangler SE', 'Wrangler Sahara', 'Wrangler X', 'Wrangler Rubicon', 'Wrangler Unlimited 4xe Sahara', 'Wrangler Unlimited Freedom Edition', 'Compass High Altitude', 'Compass Limited', 'Compass Trailhawk', 'Gladiator Overland', 'Gladiator Freedom', 'Liberty Limited', 'Grand Cherokee WK Laredo X', 'Grand Cherokee Limited', 'Wagoneer Series II 4x4', 'Wagoneer Series III', 'Grand Wagoneer Series III'],
            'Mitsubishi' => ['Lancer Evolution GSR', 'Eclipse Spyder GS', 'Eclipse GS', 'Lancer Evolution IX', 'Lancer Evolution Base', 'Outlander Sport 2.4 SE'],
        ];

        foreach ($models as $makeName => $modelNames) {
            $make = CarMake::where('name', $makeName)->first();

            if ($make) {
                foreach ($modelNames as $modelName) {
                    CarModel::create([
                        'name' => $modelName,
                        'car_make_id' => $make->id,
                    ]);
                }
            }
        }
    }
}
